export const ADD_HANDLER = 'ADD_HANDLER';
export const CANCEL_HANDLER = 'CANCEL_HANDLER';

export const START_LOADING = 'START_LOADING';
export const CANCEL_LOADING = 'CANCEL_LOADING';
export const STORE_EXPANSE = 'STORE_EXPANSE';
export const STORE_INCOME = 'STORE_INCOME';
export const STORE_EXPANSE_DETAIL = 'STORE_EXPANSE_DETAIL';
export const STORE_INCOME_DETAIL = 'STORE_INCOME_DETAIL';
export const UPDATE_EDIT = 'UPDATE_EDIT';
export const DELETE_DATA = 'DELETE_DATA';
export const UPDATE_AMOUNT = "UPDATE_AMOUNT";

export const SAVE_ITEMS = 'SAVE_ITEMS';
export const SAVE_EXPANSE = 'SAVE_EXPANSE';
export const SAVE_INCOME = 'SAVE_INCOME'

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_STATE = 'AUTH_STATE'